# Generated by Django 4.0.4 on 2022-04-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_member_age_remove_member_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100)),
                ('uzbek', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
